=== changyue258/ybt-front-app/src/main/resources/ybt-config/hxb/Agency.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Agency">
		<xs:annotation>
			<xs:documentation>代理机构</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="agencyCode">
					<xs:annotation>
						<xs:documentation>代理机构代码</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="outCode" type="xs:string">
									<xs:annotation>
										<xs:documentation>外部代码</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="messageCharset" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>报文编码格式</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="socketNetClassName" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>socket网络处理类</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="serviceClassName" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>业务处理服务类</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="businesses">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element ref="business" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="business">
		<xs:annotation>
			<xs:documentation>交易配置</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="name" type="xs:string">
					<xs:annotation>
						<xs:documentation>交易名称</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="transCode">
					<xs:annotation>
						<xs:documentation>交易代码</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="outCode" type="xs:string">
									<xs:annotation>
										<xs:documentation>交易外部代码</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element ref="messageFormat" minOccurs="0"/>
				<xs:element name="serviceClassName" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>业务处理服务类</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="ext" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="messageFormat">
		<xs:annotation>
			<xs:documentation>报文转换</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="className" type="xs:string">
					<xs:annotation>
						<xs:documentation>转换处理类</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="xsl" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="xsl">
		<xs:annotation>
			<xs:documentation>样式表信息</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="2">
				<xs:element name="path">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="req"/>
											<xs:enumeration value="rsp"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ext">
		<xs:annotation>
			<xs:documentation>扩展项</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="property"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>属性</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="value" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== changyue258/ybt-front-app/src/main/resources/ybt-config/agency-config-hxb.xml
<?xml version="1.0" encoding="UTF-8"?>
<Agency xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Agency.xsd">
	<agencyCode outCode="HXB">18</agencyCode>
	<messageCharset>GBK</messageCharset>
	<socketNetClassName>com.sinosoft.agency.hxb.HXBSocketNetImpl</socketNetClassName>
	<serviceClassName>com.sinosoft.agency.hxb.HXBService</serviceClassName>
	<businesses>
		<business>
			<name>新单核保</name>
			<transCode outCode="10">1800</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/CheckApplReqEE.xsl</path>
					<path type="rsp">format/hxb/CheckApplRespEE.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		<business>
			<name>新单承保</name>
			<transCode outCode="11">1801</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/CheckApplReqEE.xsl</path>
					<path type="rsp">format/hxb/AcceptApplRespEE.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		<!--以下分发交易配置-->
		<business>
			<name>当日撤单</name>
			<transCode outCode="12">1802</transCode>
		</business>
		<business>
			<name>保单重打</name>
			<transCode outCode="15">1802</transCode>
		</business>
		<business>
			<name>当日撤单</name>
			<transCode outCode="12">1802</transCode>
		</business>
		<business>
			<name>犹豫期退保申请</name>
			<transCode outCode="13">1803</transCode>
		</business>
		<business>
			<name>续期查询</name>
			<transCode outCode="90">1804</transCode>
		</business>
		<business>
			<name>续期缴费</name>
			<transCode outCode="91">1805</transCode>
		</business>
	</businesses>
</Agency>

=== changyue258/ybt-front-app/src/main/resources/ybt-config/hxb/agency-config-hxb.xml
<?xml version="1.0" encoding="UTF-8"?>
<Agency xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Agency.xsd">
	<agencyCode outCode="HXB">08</agencyCode>
	
	<messageCharset>GBK</messageCharset>

	<socketNetClassName>com.sinosoft.agency.hxb.HXBSocketNetImpl</socketNetClassName>

	<serviceClassName>com.sinosoft.agency.hxb.HXBService</serviceClassName>
	
	<businesses>
	
		<!-- 柜面渠道 -->
		<business>
			<name>新单核保</name>
			<transCode outCode="OPR001">01</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/CheckApplReq.xsl</path>
					<path type="rsp">format/hxb/CheckApplResp.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		
		<!-- 电子渠道 -->
		<business>
			<name>新单核保</name>
			<transCode outCode="10">01</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/CheckApplReqEE.xsl</path>
					<path type="rsp">format/hxb/CheckApplRespEE.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		
		<!-- 柜面渠道 -->
		<business>
			<name>新单承保</name>
			<transCode outCode="OPR011">02</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/AcceptApplReq.xsl</path>
					<path type="rsp">format/hxb/AcceptApplResp.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		
		<!-- 电子渠道 -->
		<business>
			<name>新单承保</name>
			<transCode outCode="11">0102</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/CheckApplReqEE.xsl</path>
					<path type="rsp">format/hxb/AcceptApplRespEE.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		
		<!-- 柜面渠道 -->
		<business>
			<name>当日撤单</name>
			<transCode outCode="OPR911">03</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/CancelApplReq.xsl</path>
					<path type="rsp">format/hxb/CancelApplResp.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		
		<!-- 电子渠道 -->
		<business>
			<name>当日撤单</name>
			<transCode outCode="12">03</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/CancelApplReqEE.xsl</path>
					<path type="rsp">format/hxb/CancelApplRespEE.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		
		<!-- 柜面渠道 -->
		<business>
			<name>保单重打</name>
			<transCode outCode="SPE002">04</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/PrintPolicyReq.xsl</path>
					<path type="rsp">format/hxb/PrintPolicyResp.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		
		<!-- 电子渠道和柜面渠道相同 -->
		<business>
			<name>犹豫期退保申请</name>
			<transCode outCode="13">12</transCode>
			<messageFormat>
				<className>com.sinosoft.ybframework.gateway.provider.XmlMessageFormatProvider</className>
				<xsl>
					<path type="req">format/hxb/ApplyHesCancelCntrReq.xsl</path>
					<path type="rsp">format/hxb/ApplyHesCancelCntrResp.xsl</path>
				</xsl>
			</messageFormat>
		</business>
		
	</businesses>
</Agency>
